name: buildimage

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    
jobs:
  buildimage:
    name: buildimage
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.LGDOCKERHUBUSERNAME }}
        password: ${{ secrets.LGDOCKERHUBPWD }}
    - name: Build and push to dockerhub
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          longguikeji/nginx:reload
